import { CATEGORIES, FOODS } from "../domain/constants";
import { round } from "../domain/tracker";
import type { TrackerController } from "../hooks/useTrackerController";
import { CategoryWheel } from "./CategoryWheel";
import { FoodCard } from "./FoodCard";
import { FoodIcon } from "./FoodIcon";
import "./FoodScreen.css";
export function FoodScreen({ controller: c }: {
    controller: TrackerController;
}) { return <div className="food-screen">{c.selectedCategory === null ? <section className="category-section"><CategoryWheel onSelect={c.openFoodCategory}/></section> : <><div className="category-header"><button className="back-button" onClick={c.closeFoodCategory}>← Kategorije</button><div><span className="eyebrow">OTVORENO</span><h2>{c.selectedCategory === "common" ? "Osnovno" : CATEGORIES.find((category) => category.id === c.selectedCategory)?.name}</h2></div></div>{c.categoryFoods.length > 0 ? <div className="food-list">{c.categoryFoods.map((food) => <FoodCard key={food.id} food={food} selectedAmount={c.draft.foods.find((item) => item.foodId === food.id)?.amount} common={c.commonFoods.includes(food.id)} pendingHide={c.pendingHideFoods.includes(food.id)} onSelect={c.selectFood} onCommon={c.toggleCommonFood}/>)}</div> : <div className="card common-empty">{c.selectedCategory === "common" && c.commonFoods.length === 0 ? "Označi zvezdicom namirnice koje želiš u Osnovno." : "U ovoj kategoriji nema vidljivih namirnica."}</div>}{c.hiddenCategoryFoods.length > 0 && <section className={`hidden-food-section ${c.showHiddenFoods ? "open" : ""}`}><button className={`hidden-food-toggle ${c.showHiddenFoods ? "active" : ""}`} onClick={() => c.setShowHiddenFoods((current) => !current)} aria-expanded={c.showHiddenFoods}>{c.showHiddenFoods ? "Sakrij završene" : `Prikaži skrivene (${c.hiddenCategoryFoods.length})`}</button>{c.showHiddenFoods && <div className="hidden-food-panel"><div className="hidden-food-heading"><span className="eyebrow">SKRIVENO DANAS</span><strong>Već unete namirnice</strong></div><div className="food-list">{c.hiddenCategoryFoods.map((food) => <FoodCard key={food.id} food={food} selectedAmount={c.draft.foods.find((item) => item.foodId === food.id)?.amount} common={c.commonFoods.includes(food.id)} pendingHide={false} onSelect={c.selectFood} onCommon={c.toggleCommonFood}/>)}</div></div>}</section>}</>}<div className="food-totals"><strong>{round(c.nutrition.kcal).toLocaleString("sr-RS")} kcal</strong><span>{round(c.nutrition.protein)} g proteina</span></div><section className={`card today-foods ${c.showTodayFoods ? "open" : ""}`}><button className="today-foods-trigger" onClick={() => c.setShowTodayFoods((current) => !current)} aria-expanded={c.showTodayFoods}><div><span>DANAŠNJI UNOS</span><strong>{c.draft.foods.length ? `${c.draft.foods.length} ${c.draft.foods.length === 1 ? "namirnica" : c.draft.foods.length < 5 ? "namirnice" : "namirnica"}` : "Još nema hrane"}</strong></div><b aria-hidden="true">⌄</b></button><div className="today-foods-reveal"><div className="today-foods-list">{c.draft.foods.map((selection) => { const food = FOODS.find((item) => item.id === selection.foodId); if (!food)
    return null; const amount = food.unit === "šejk" ? `${selection.amount}×` : `${selection.amount} ${food.unit}`; return <div className="today-food-row" key={food.id}><span className="today-food-icon"><FoodIcon food={food}/></span><strong>{food.name}</strong><span>{amount}</span></div>; })}</div></div></section></div>; }
